[package]
name = "winbackup-fuse"
version = "0.1.0"
edition = "2021"

[dependencies]
encoding_rs = "0.8.32"
fuser = "0.12.0"
glob = "0.3.1"
indicatif = "0.17.5"
libc = "0.2.147"
ouroboros = "0.17.2"
zip = "0.6.6"
